DATA USE AGREEMENT

Project Title:
Effective Date:
Project Duration: [Start date] to [End date]

1. Parties

This Data Use Agreement (“Agreement”) is between:

Farm / Data Provider:

Farm Name: [Farm name]
Farm Representative: [Name and title]
Contact: [Contact information]

Student / Researcher:

Student Name: [Student name]
Institution: [University / College]
Program / Department: [Program or department]
Supervisor: [Supervisor name, if applicable]
Contact: [Contact information]

Together, the farm and student are referred to as “the Parties.”

2. Project Scope and Intended Use

Research Purpose:
[Briefly describe the research question, project, or study.]

Project Scope:
[Describe what the student will study and the activities that will take place on or using information from the farm.]

Intended Use of Data:

The data provided or collected under this Agreement will be used for:

[Student research project / thesis / dissertation]
[Academic analysis]
[Class assignment or academic report, if applicable]
[Publication or presentation, if agreed]
[Other permitted use]

The student will not use the data for purposes outside the scope of this Agreement without obtaining permission from the farm.

3. Data to Be Collected and Methods
3.1 Data Provided by the Farm

The farm may provide the following existing data:

Animal health records
Weather or Environmental records of the farm
Farm management practices
3.2 Data Collected by the Student

The student may collect:

Animal observational data
Measurements
Photographs or videos of the animals in the farm
3.3 Collection Methods

Collection methods:

Collection period:

Farm access:
The student will coordinate visits and data collection activities with the farm and will follow reasonable farm safety, biosecurity, and operational requirements.

4. Data Ownership and Intellectual Property
4.1 Farm Data

Data originally provided by the farm remains the property of the farm unless otherwise agreed in writing. The student is authorized to collect, use, analyze, and retain data during the research project for academic research purposes, subject to the confidentiality, data protection, ownership, and publication provisions of this Agreement

4.2 Student-Generated Data

Data collected or generated by the student during the research will be owned by the farm unless otherwise agreed in writing. The student is authorized to collect, use, analyze, and retain data generated during the research project for academic research purposes, subject to the confidentiality, data protection, ownership, and publication provisions of this Agreement

4.3 Research Outputs

The student may use the data to prepare:

Research paper
Academic presentation

Any use of the farm's name, identifying information, photographs, or commercially sensitive information will be prohibited unless separately agreed.

5. Confidentiality and Privacy

The student agrees to keep confidential any non-public information provided by the farm.

Examples of confidential information may include:

Financial information
Production information
Business practices
Customer or employee information
Proprietary farming practices
Farm records
Information identified by the farm as confidential

The student will not disclose confidential information to third parties except where required by the student's institution or applicable by law, or where the farm has provided permission.

6. Data Security

The student will take reasonable measures to protect the data from unauthorized access, loss, or disclosure.

Storage location:

Authorized users: Research team and supervisor(s)

Security requirements:

If data are lost, disclosed, or accessed without authorization, the student will notify the farm as soon as reasonably possible.

7. FAIR Principles

Where appropriate and consistent with confidentiality and the farm's rights, the student will manage research data according to the FAIR principles.

Findable:
The research project will have a designated GitHub repository containing the research code, analysis notebooks, documentation, and other relevant research materials. The repository will not contain the underlying farm data.The GitHub repository may be publicly accessible, where appropriate, to support discovery and transparency of the research methods and outputs. The underlying farm data will remain separate from the repository and will not be publicly accessible.

Accessible:
Access to the underlying farm data will be restricted to the authorized research team. Members of the public may access the GitHub repository and its research materials but will not have access to the farm data. Data access will be controlled through [secure storage / institutional repository / other access-controlled system]. The farm data will not be publicly shared or distributed without the farm's permission.

Interoperable
Research code, notebooks, and documentation will use appropriate and commonly supported formats where practical.Data formats, metadata, and documentation will be maintained in a manner that allows authorized members of the research team to access, analyze, and interpret the data.

[Specify data formats, standards, or metadata practices.]

Reusable
The research team will provide appropriate documentation of the research methods, analytical procedures, data provenance, and relevant metadata to support reproducibility and responsible reuse of the research materials. The GitHub repository may contain reusable research code and notebooks but will not contain the underlying farm data. Any reuse of the farm data will be limited to the purposes authorized under this Agreement and will remain subject to the farm's confidentiality, ownership, and data-use restrictions. FAIR data practices will not require the student to make confidential or commercially sensitive farm information publicly available.

8. Data Sharing and Publication

The student may share or publish research findings resulting from the project subject to the conditions below:

Data may be shared publicly: No
Aggregated or anonymized data may be shared: Yes
Farm name may be identified: Only with written permission
Farm representative may review publications before submission: For a specific time-period which will be discussed prior, if applicable

The student will make reasonable efforts to ensure that published results do not unintentionally disclose confidential or commercially sensitive information.

9. Data Repository and Retention

Repository / Storage Location:

Person responsible for the data:

Data retention period: At the end of the retention period, the data will be destroyed by the institution.

10. Timeline of Data Sharing
Activity	Date / Period	Responsible Party
Agreement begins	[Date]	Both parties
Data provided by farm	[Date]	Farm
Student data collection	[Dates]	Student
Data analysis	[Dates]	Student
Draft research output	[Date]	Student
Final research output	[Date]	Student
Data repository/retention begins	[Date]	[Party]
Agreement ends	[Date]	Both parties
11. Farm Responsibilities

The farm agrees to:

Provide the data or access specifically identified in this Agreement.
Identify information that should be treated as confidential.
Provide reasonable access to the farm for agreed research activities.
Inform the student of relevant safety, biosecurity, and operational requirements.
Notify the student of any restrictions on the use or sharing of farm data.
12. Student Responsibilities

The student agrees to:

Use the data only for the agreed research purposes.
Collect and manage data responsibly.
Protect confidential information.
Follow farm safety and operational requirements.
Follow applicable university/institutional research requirements.
Properly document data collection and provenance.
Acknowledge the farm's contribution where appropriate.
Obtain permission before using the farm's identifying information beyond the agreed purposes.
13. Termination

Either Party may request termination of this Agreement by providing [number] days' notice.

Upon termination:

The student will stop collecting new data unless otherwise agreed.
The Parties will determine whether existing data should be returned, deleted, or retained.
Confidentiality obligations will continue after termination.
Any previously authorized academic outputs may proceed subject to the terms of this Agreement.
14. Changes to the Agreement

Any changes to this Agreement should be documented and agreed to by both Parties in writing.

15. Signatures
Farm / Data Provider

Name: ______________________________

Title: _______________________________

Farm: ________________________________

Signature: ___________________________

Date: ________________________________

Student / Researcher

Name: ______________________________

Institution: __________________________

Program: _____________________________

Signature: ___________________________

Date: ________________________________

Faculty Supervisor, if applicable

Name: ______________________________

Institution: __________________________

Signature: ___________________________

Date: ________________________________
